// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_content: dynamic(() => import("./AboutContent")),
  call_to_action: dynamic(() => import("./CallToAction")),
  chip: dynamic(() => import("./Chip")),
  colors: dynamic(() => import("./Colors")),
  cta: dynamic(() => import("./Cta")),
  darker: dynamic(() => import("./Darker")),
  double_text: dynamic(() => import("./DoubleText")),
  image_opener: dynamic(() => import("./ImageOpener")),
  mounting: dynamic(() => import("./Mounting")),
  opener: dynamic(() => import("./Opener")),
  power: dynamic(() => import("./Power")),
  space: dynamic(() => import("./Space")),
  specs: dynamic(() => import("./Specs")),
  thickness: dynamic(() => import("./Thickness")),
  welcome: dynamic(() => import("./Welcome")),
};
